<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'CommentInstructions' => 'Puoi usare questo modulo per mandarci le tue valutazioni o domande sul sito Hostelz.com. <p>Nota: <b><i>Non possiamo rispondere a domande su ostelli o specifiche mete di viaggio.</i> </i><b> Le uniche informazioni che abbiamo sugli ostelli e le destinazioni sono già presenti sul sito, e tutti i recapiti disponibili per ciascuna sistemazione sono segnalati nello spazio ad essa destinato. Hostelz.com è una guida comprendente migliaia di ostelli e sistemazioni a basso costo. <p><b>Se stai tentando di contattare un ostello o un albergo in particolare, torna alla pagina ad esso dedicata, in cima alla quale troverai i recapiti.</b> Tutte le informazioni al riguardo a nostra disposizione sono elencate in quello spazio.<p> Normalmente rispondiamo alla maggior parte delle e-mail nel giro di 1-2 giorni lavorativi.',
    'Message' => 'Messaggio',
    'MessageSent' => 'Il tuo messaggio è stato inviato. Grazie.',
    'SendIt' => 'Invia',
    'Subject' => 'Oggetto',
    'YourEmailAddress' => 'Il tuo indirizzo e-mail',
    'YourName' => 'Il tuo nome',
];
