<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'CentralEastAsia' => 'Asia Centrale & Orientale',
    'CentralSouthAmerica' => 'America Centrale e Sudamerica',
    'EasternEuropeRussia' => 'Europa dell\'Est & Russia',
    'MexicoCaribbean' => 'Messico & Caraibi',
    'MiddleEast' => 'Medio Oriente',
    'NorthAmerica' => 'Nordamerica',
    'SouthSoutheastAsia' => 'Asia Meridionale & Sudorientale',
    'UKIreland' => 'UK & Irlanda',
    'WesternEurope' => 'Europa Occidentale',
];
