<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'closing' => 'Distinti saluti,',
    'initialEmail' => 'Salve. Benvenuti su Hostelz.com. :hostelname è ora inserito su Hostelz.com. Ecco un modulo online per completare o modificare le informazioni presenti sul vostro profilo (vi suggeriamo di salvare questa URL anche per gli aggiornamenti futuri):<br><br> :managementLink<br><br>Vi ricordiamo che le inserzioni su Hostelz.com sono completamente gratuite. Vi invitiamo a contattarci in caso di necessità. Grazie.',
    'maybeInitialEmail' => 'Salve. :hostelname è inserito su Hostelz.com. Ecco un modulo online per completare o modificare le informazioni presenti sul vostro profilo (vi suggeriamo di salvare questa URL anche per gli aggiornamenti futuri):<br><br> :managementLink<br><br>Abbiamo recentemente aggiunto delle nuove funzioni, incluse la possibilita\' di inserire le descrizioni del vostro profilo in più lingue. Per favore, assicuratevi che tutte le informazioni siano complete ed aggiornate. <br><br>Come sempre, le nostre inserzioni sono completamente gratuite.  Vi invitiamo a contattarci in caso di necessità. Grazie.',
    'newFields' => 'Salve. Hostelz.com ha recentemente aggiunto dei nuovi campi al database che vi invitiamo a riempire. Ecco il link per l’aggiornamento del profilo:<br>   :managementLink<br><br>Per favore, assicuratevi di aver salvato questa URL in modo da procedere con più facilità ai prossimi aggiornamenti. Qualora necessitiate di ulteriori chiarimenti, non esitate a contattarci.',
    'TextBelow' => '(Versione italiana in calce)',
];
