<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'Cancel' => 'Annulla',
    'ContactHostelz' => 'Contatta',
    'Continue' => 'Continua',
    'FindHostelsIn' => 'Trova ostelli a:',
    'free' => 'Gratis',
    'Home' => 'Guida ostelli',
    'NewListing' => 'Aggiungi un nuovo ostello',
    'pay' => 'A pagamento',
    'propertyTypePlural' => [
        'Apartment' => 'Appartamenti',
        'Campsite' => 'Campeggi e Bungalow',
        'Hostel' => 'Ostelli',
        'Hotel' => 'Alberghi',
        'Other' => 'Altro',
    ],
    'Search' => 'Cerca',
    'Submit' => 'Invia',
    'tagline' => 'Recensioni di ostelli in tutto il mondo',
    'yes' => 'Sì',
];
