<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'BecomeAMemberAnswer' => 'Generalmente devi essere un membro per poter essere accolto da un ostello HI. Se non sei un membro, è possibile che ti accolgano in cambio di un sovrapprezzo per ogni notte, perciò si consiglia l’acquisto di una tessera associativa prima della partenza. Una tessera HI ti consentirà di ottenere sconti su migliaia di altri prodotti e servizi per viaggiatori in tutto il mondo. <p>La tua tessera HI può essere usata in ostelli in tutto il mondo, ma è necessario acquistarla dall’associazione HI del tuo paese d’origine.',
    'BecomeAMemberQuestion' => 'Devo essere un membro per soggiornare in un ostello HI?',
    'DescriptionOfHI' => 'Hostelling International (HI) è l’organizzazione mondiale “ufficiale” degli ostelli (un tempo nota come International Youth Hostel Federation, o IYHF). HI è un’organizzazione senza scopo di lucro che rappresenta le associazioni degli ostelli di oltre 60 paesi, con un totale di oltre 4000 ostelli. Gli ostelli HI  seguono un certo standard di qualità e sono generalmente puliti e sicuri. E in molti posti nel mondo, specialmente nelle città più piccole, gli ostelli HI sono probabilmente gli unici ostelli sul posto. (A proposito, Hostelz.com non è affiliato con HI né con altre organizzazioni. Noi segnaliamo ostelli HI, ostelli appartenenti ad altre associazioni di ostelli e ostelli indipendenti.)',
    'GetACard' => 'Acquista una tessera Hostelling International...',
    'OtherResidents' => 'Per residenti in altri paesi',
    'USResidents' => 'Per residenti negli Stati Uniti',
    'WhatIsHI' => 'Cos’è HI?',
];
