<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'EnterAName' => 'Inserisci il nome di una città, di un paese, o di un ostello e clicca su Invio.',
    'OnlyWebsiteEverNeed' => 'The only hostels website you\'ll ever need.',
    'PopularCities' => 'Città principali:',
];
