<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'HereIsSomeHTML' => 'Grazie per aver aggiunto un link a Hostelz.com sul tuo sito web! Ecco qualche esempio di HTML che può essere usato per il link al nostro sito:',
    'LinkToHostelz' => 'Inserisci un link a Hostelz.com',
    'LinkWithAnImage' => 'O, se preferisci un link con un’immagine, puoi usare questo:',
    'LooksLikeThis' => 'Appare così...',
];
