<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'submitRatingText' => 'Hai soggiornato in questo alloggio? Aiuta la tua comunità ostello lasciando una recensione dettagliata.',
    'submitRatingTextLoggedUser' => "Ciao Pavel, hai soggiornato all'Ecomama Hostel? Lascia la tua recensione qui.",
    'createAccount' => '<a href=":url">Crea</a> il tuo account gratuito per tenere traccia del vostro portafoglio ostello.',
];
