<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'ArticleBy' => 'por :name',
    'Articles' => 'Artigos',
    'ArticlesDesc' => 'Artigos sobre albergues e viagem do Hostelz.com.',
];
