<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'Africa' => 'África',
    'AustraliaOceania' => 'Austrália & Oceania',
    'CentralEastAsia' => 'Ásia Central e Leste Asiático',
    'CentralSouthAmerica' => 'América do Sul e América Central',
    'EasternEuropeRussia' => 'Leste da Europa e Rússia',
    'MexicoCaribbean' => 'México e Caribe',
    'MiddleEast' => 'Oriente Médio',
    'NorthAmerica' => 'América do Norte',
    'SouthSoutheastAsia' => 'Sul e Sudeste Asiático',
    'UKIreland' => 'Reino Unido e Irlanda',
    'WesternEurope' => 'Oeste da Europa',
];
