<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'CommentInstructions' => 'Você pode usar este formulário para nos enviar seu feedback ou perguntas sobre o site Hostelz.com. <p>Nota: <b><i>Nós não podemos responder perguntas sobre hostels ou locais de viagem em particular.</i></b> As informações que temos sobre albergues e viagem estão no site e todas as informações de contato que temos estão listadas nos anúncios. Hostelz.com é um guia de hostels com anúncios de milhares de hostels e acomodações econômicas. <p><b>Se está tentando entrar em contato com um hostel ou hotel em particular, volte e procure pelas informações de contato na seção "Localização/Contato" no anúncio do estabelecimento.</b> Todas as informações de contato que temos para o estabelecimento está listada lá.<p>Nós geralmente respondemos a maioria dos emails em 1-2 dias úteis.',
    'Message' => 'Mensagem',
    'MessageSent' => 'Sua mensagem foi enviada. Obrigado.',
    'SendIt' => 'Enviar',
    'Subject' => 'Assunto',
    'YourEmailAddress' => 'Seu endereço de Email',
    'YourName' => 'Seu Nome',
];
