<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'closing' => 'Atenciosamente,',
    'initialEmail' => 'Oi. :hostelname agora está listado no Hostelz.com, mas precisamos que complete as informações do anúncio:<br><br> :managementLink<br><br>Nossos anúncios são totalmente gratuitos, então não há cobrança para anunciar no site. Deixe-me saber se lhe restam dúvidas. Obrigado.',
    'listingIncomplete' => 'Olá. As informações do seu anúncio no Hostelz.com estão incompletas (talvez nós tenhamos adicionado novos campos desde a última vez que você atualizou suas informações). Por favor, complete as informações do seu anúncio no Hostelz.com:<br><br> :managementLink<br><br>Claro, os anúncios no Hostelz.com são sempre gratuitos, então não há cobrança para anunciar em nosso site. Deixe-me saber se lhe restam dúvidas.',
    'maybeInitialEmail' => 'Olá. :hostelname está listado no Hostelz.com, mas nós precisamos atualizar e completar as informações do seu anúncio:<br><br> :managementLink<br><br>Nós recentemente adicionamos novas características. Por favor tenha certeza de que todas as informações estão completas e atualizadas.<br><br>Como sempre, nossos anúncios são sempre gratuitos, então não há cobrança para anunciar neste site. Deixe-me saber se lhe restam dúvidas. Obrigado.',
    'newFields' => 'Olá. O Hostelz.com recentemente adicionou alguns campos em nosso banco de dados e precisamos que complete seu anúncio com algumas informações adicionais.<br><br>Por favor, atualize seu anúncio:<br><br> :managementLink<br><br> Deixe-me saber se lhe restam dúvidas.',
    'newlySubmittedListing' => 'Olá. Obrigado por cadastrar :hostelname no Hostelz.com. Por favor complete as informações do seu anúncio:<br><br> :managementLink<br><br>Nossos anúncios são totalmente gratuitos, então não há cobrança para estar listado no site. Deixe-me saber se lhe restam dúvidas. Obrigado.',
    'TextBelow' => '(Tradução em Inglês Abaixo)',
];
