<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'BecomeAMemberAnswer' => 'Geralmente deve-se ser membro HI para ficar em um HI hostel. Se não é membro pode ser que possa se hospedar pagando uma taxa extra por noite, mas é melhor comprar um cartão de sócio antes de sair de viagem. Um cartão HI também lhe dá descontos em milhares de produtos e serviços relacionados a viagem ao redor do mundo. <p>Seu cartão de sócio HI pode ser usado em albergues de qualquer lugar do mundo, mas você deve comprar seu cartão de sócio na associação HI do seu país.',
    'BecomeAMemberQuestion' => 'Eu tenho que me tornar membro pra ficar em um Albergue da Juventude(HI hostel)?',
    'DescriptionOfHI' => 'A Hostelling International (HI) é a organização mundial "oficial" de albergues (geralmente chamada de Federação Internacional dos Albergues da Juventude, ou FIAJ, "IYHF" em Inglês). HI é uma organização sem fins lucrativos que representa associações de hostels em mais de 60 países, com um total de mais de 4000 albergues. HI hostels (Albergues da Juventude) mantém um certo nível de qualidade e são geralmente limpos e seguros. Em muitos lugares do mundo, especialmente em cidades menores, o HI hostel será provavelmente o único na cidade. (A propósito, Hostelz.com não é afiliado à HI ou qualquer outro grupo. Nós anunciamos os HI Hostels, hostels pertencentes a outros grupos hosteleiros e hostels independentes.)',
    'GetACard' => 'Obter um cartão de membro da Hostelling International...',
    'OtherResidents' => 'Para residentes de Outros Países',
    'USResidents' => 'Para residentes dos Estados Unidos',
    'WhatIsHI' => 'O que é HI?',
];
