<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'EnterAName' => 'Insira uma cidade, país ou o nome de um hostel.',
    'ListingsIn' => ':hostelCount anúncios em :cityCount cidades.',
    'OnlyWebsiteEverNeed' => 'O único site de hostels que você irá precisar.',
    'PopularCities' => 'Cidades em Destaque:',
    'tagline1' => 'Compare os preços em todos os sistemas de reserva online de uma só vez.',
    'tagline2' => 'Comentários verdadeiros e sem censura que você pode confiar.',
    'tagline3' => 'Informações completas de hostels no mundo todo.',
    'WelcomeTo' => 'Bem-vindo ao maior catálogo de hostels do mundo.',
];
