<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'translated' => [
        'de' => 'Alemão',
        'en' => 'Inglês',
        'es' => 'Espanhol',
        'fr' => 'Francês',
        'it' => 'Italiano',
        'ja' => 'Japonês',
        'pt-br' => 'Português (Brasileiro)',
    ],
];
