<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'HereIsSomeHTML' => 'Obrigado por adicionar um link para o Hostelz.com no seu website! Aqui há um exemplo do HTML que pode ser usado para direcionar ao nosso site:',
    'LinkToHostelz' => 'Redirecione para o Hostelz.com',
    'LinkWithAnImage' => 'Ou se você quer inserir um link com uma imagem, pode usar este como opção:',
    'LooksLikeThis' => 'Se parece com isso...',
];
