<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'submitRatingText' => 'Ficou neste alojamento? Ajude a sua comunidade Hostel, deixando uma revisão detalhada.',
    'submitRatingTextLoggedUser' => ':name, ficaste no :hostelName Hostel? Deixe a sua crítica aqui.',
    'createAccount' => '<a href=":url">Crie</a> sua conta gratuita para manter o controle de seu portfólio hostel.',
];
