<?php

/* dumped from the old website.  may be useful for moving to the new site. */
return [
    '_translationInfo' => [
    ],
    'TextBelow' => '(English Translation Below)',
    'newlySubmittedListing' => 'Hi.  Thank you for submitting :listingName to Hostelz.com.  Please complete your listing information:<br><br> :managementLink<br><br>Our listings are completely free, so there is no charge to be listed on the site. Let me know if you have any questions.  Thanks.',
    'maybeInitialEmail' => 'Hi.  :listingName is listed on Hostelz.com, but we need you to update and complete your listing information:<br><br> <a href=":managementLink">:managementLink</a><br><br>We have recently added new features.  Please check to make sure all of your information is complete and up to date.<br><br>As always, our listings are completely free, so there is no charge to be listed on the site.  Let me know if you have any questions.  Thanks.',
    'initialEmail' => 'Hi.  :listingName is now listed on Hostelz.com, but we need you to complete your listing information:<br><br> :managementLink<br><br>Our listings are completely free, so there is no charge to be listed on the site. Let me know if you have any questions.  Thanks.',
    'newFields' => 'Hi.  Hostelz.com has recently added some new fields to our database and we need you to complete some additional information for your listing.  Please update your listing:<br><br> :managementLink<br><br>If you have any questions, just let me know.',
    'listingIncomplete' => 'Hi.  Your listing information on Hostelz.com is incomplete (we may have added some new fields since the last time you entered your information).  Please complete the information for your Hostelz.com listing:<br><br> :managementLink<br><br>Of course listings on Hostelz.com are always free, there is no fee to be listed on our site.  If you have any questions, just let me know.',
    'awardSticker_hasManager' => 'We are pleased to now designate :listingName as an official Hostelz.com Recommended Hostel based on your Hostelz.com Overall Score.  The Hostelz.com Overall Score is calculated from a combination of your guest reviews on all of the major hostel websites, and it is considered to be the ultimate and definitive guest approval rating for hostels.<br><br>We would like to mail you an award in recognition of your hostel\'s achievement, but first you will need to verify the mailing address we have in our database for your hostel.  Please login to Hostelz.com and update the listing with your listing management account.  If you need any assistance with that, please let me know.',
    'awardSticker_noManager' => 'We are pleased to now designate :listingName as an official Hostelz.com Recommended Hostel based on your Hostelz.com Overall Score.  The Hostelz.com Overall Score is calculated from a combination of your guest reviews on all of the major hostel websites, and it is considered to be the ultimate guest approval rating for hostels.<br><br>We would like to mail you an award in recognition of your hostel\'s achievement, but first you will need to verify the mailing address we have in our database for your hostel.  Please use this link to set up your user account so you can update the mailing address and other information for your listing:<br><br> :managementLink',
    'awardSticker_hasMailingAddress' => 'We are pleased to now designate :listingName as an official Hostelz.com Recommended Hostel based on your Hostelz.com Overall Score.  The Hostelz.com Overall Score is calculated from a combination of your guest reviews on all of the major hostel websites, and it is considered to be the ultimate guest approval rating for hostels.<br><br>We would like to mail you an award in recognition of your hostel\'s achievement.  It will be mailed to this address:<br><br>:mailingAddress<br><br>If the address isn\'t correct, please login to Hostelz.com and then click on your email address at the top of the page to find the Listing Management link.  If you need any assistance with that, please let me know.',
    'closing' => 'Best regards,',
];
