<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'ArticleBy' => 'par :nom',
    'Articles' => 'Articles',
    'ArticlesDesc' => 'Articles sur les auberges et séjours sur Hostelz.com.',
];
