<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'Africa' => 'Afrique',
    'AustraliaOceania' => 'Australie & Océanie',
    'CentralEastAsia' => 'Asie Centrale et Asie du Sud-Est',
    'CentralSouthAmerica' => 'Amérique Centrale et Amérique du Sud',
    'EasternEuropeRussia' => 'Europe de l\'Est et Russie',
    'MexicoCaribbean' => 'Mexique & Caraïbes',
    'MiddleEast' => 'Moyen Orient',
    'NorthAmerica' => 'Amérique du Nord',
    'SouthSoutheastAsia' => 'Asie du Sud et Asie du Sud-Est',
    'UKIreland' => 'Royaume-Uni & Irlande',
    'WesternEurope' => 'Europe de l\'Ouest',
];
