<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'CommentInstructions' => 'Vous pouvez utiliser ce formulaire pour nous faire parvenir vos impressions ou questions concernant le site Internet Hostelz.com. <p>Notez: <b> <i> Nous ne pouvons répondre aux questions qui concernent une auberge de jeunesse en particulier ou une destination de voyage.</i></b>  Nous sommes un guide proposant des milliers d’auberges de jeunesse. <p><b>Si vous souhaitez contacter une auberge en particulier, faites retour et rechercher le contact en haut de la page de la liste des auberges. .</b> Tous los contacts et informations que nous possédons y sont listés. <p>Nous répondons à quasiment tous les emails sous 1-2 jours ouvrés.',
    'MessageSent' => 'Votre message à bien été envoyé. Merci.',
    'SendIt' => 'Envoyer',
    'Subject' => 'Sujet',
    'YourEmailAddress' => 'Votre adresse email',
    'YourName' => 'Votre nom',
];
