<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'closing' => 'Cordialement,',
    'initialEmail' => 'Bonjour.  :hostelname est désormais listé sur Hostelz.com, mais nous avons besoin que vous complétiez vos informations:<br><br> :managementLink<br><br>Nos listes sont complètement gratuites, il n\'y a donc aucun frais pour être listé sur le site. Faites-moi savoir si vous avez des questions.  Merci.',
    'listingIncomplete' => 'Bonjour.  Vos informations sur Hostelz.com sont incomplètes (il se peut que nous ayons ajoutés de nouveaux champs depuis la dernière fois que vous avez entré vos informations).  Merci de complétez les informations de votre page sur Hostelz.com:<br><br> :managementLink<br><br>Bien entendu, nos listes sont complètement gratuites, il n\'y a donc aucun frais pour être listé sur le site. Faites-moi savoir si vous avez des questions.  Merci.',
    'maybeInitialEmail' => 'Bonjour.  :hostelname est listé sur Hostelz.com, mais nous avons besoin que vous mettiez à jour et complétiez vos informations:<br><br> :managementLink<br><br>Nous avons ajouté récemment de nouvelles options.  Merci de vérifier que toutes les informations sont complètes et à jour.<br><br>Comme toujours, nos listes sont complètement gratuites, il n\'y a donc aucun frais pour être listé sur le site. Faites-moi savoir si vous avez des questions.  Merci.',
    'newFields' => 'Bonjour.  Hostelz.com a récemment ajouté de nouveaux champs a sa base de données et nous avons besoin que vous complétiez vos informations.  Merci de mettre à jour votre page:<br><br> :managementLink<br><br>Faites-moi savoir si vous avez des questions..',
    'newlySubmittedListing' => 'Bonjour.  Merci d\'avoir ajouté :hostelname à Hostelz.com.  Merci de compléter vos informations:<br><br> :managementLink<br><br>Nos pages sont totalement gratuites, il n\'y a donc aucun frais pour être listé sur le site. Faites-moi savoir si vous avez des questions.  Merci.',
    'TextBelow' => '(Traduction anglaise ci-dessous)',
];
