<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'AboutHostelz' => 'A Propos de Hostelz.com',
    'AffiliateProgram' => 'Programme de partenariat',
    'ContactHostelz' => 'Contacter Hostelz.com',
    'Copyright' => 'Tous droits réservés © :year Hostelz.com',
    'FindHostelsIn' => 'Rechercher une auberge à :',
    'Home' => 'Guide des Auberges',
    'NewListing' => 'Ajouter une Nouvelle Auberge de Jeunesse',
    'PortionOfProceeds' => 'Une partie des bénéfices sont reversés à :charityName',
    'PrivacyPolicy' => 'Charte de confidentialité',
    'Search' => 'Rechercher',
    'Select' => 'Sélectionner',
];
