<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'BecomeAMemberAnswer' => 'Vous devez généralement être membre de l’organisation HI pour séjourner dans une de leurs auberges. Si vous n’êtes pas membre, vous pouvez cependant séjourner dans l’auberge moyennant un coût supplémentaire par nuit. Il est plus accommodant d’acheter une carte d’adhérant avant votre départ. Une carte HI vous permet de bénéficier de remises sur des milliers d’articles et services liés au voyage, où que vous soyez dans le monde. <p> Votre carte de membre HI peut être utilisée dans toutes les auberges de jeunesse. Cependant il vous faut acheter la carte d’abonnement auprès de l’association HI de votre pays de résidence.',
    'BecomeAMemberQuestion' => 'Dois-je devenir membre pour séjourner dans une auberge de jeunesse HI ?',
    'DescriptionOfHI' => 'Hostelling International (HI) est l’organisation "officielle" des auberges de jeunesse dans le monde (aussi connue sous le nom International Youth Hostel Federation, ou IYHF). HI est une organisation bénévole représentant les associations d’hôtellerie de plus de 60 pays, avec plus de 4000 auberges de jeunesses répertoriées. Les auberges proposées sont de qualités et sont généralement propres et sûres. Pour beaucoup d’endroits dans monde, spécialement les petites villes, l’auberge de jeunesse HI est probablement la seule auberge de la ville. (Pour précision, Hostelz.com n’est pas affilié á HI ou aucun autre groupe. Nous répertorions les auberges de jeunesse HI, auberges de jeunesse affiliées à d’autres groupes d’hôtellerie ainsi que des auberges de jeunesse indépendantes).',
    'GetACard' => 'Se procurer une carte de membre Hostelling International...',
    'OtherResidents' => 'Vous résidez dans un autre pays',
    'USResidents' => 'Vous résidez aux Etats-Unis',
    'WhatIsHI' => 'Qu’est-ce que HI?',
];
