<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'EnterAName' => 'Entrer une ville, un pays, ou le nom d’une auberge<br>appuyer ensuite sur entrer pour valider.',
    'ListingsIn' => ':hostelCount entrées dans :cityCount villes.',
    'OnlyWebsiteEverNeed' => 'Le seul site web d\'auberges pour satisfaire tous vos besoins.',
    'PopularCities' => 'Villes Populaires:',
    'WelcomeTo' => 'Bienvenue sur la base de données d\'auberges la plus grande au monde.',
];
