<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'HereIsSomeHTML' => 'Merci d\'avoir ajouté un lien vers Hostelz.com sur votre site web!  Voici un échantillo de code HTML que vous pouvez utiliser pour mettre un lien vers notre site:',
    'LinkToHostelz' => 'Mettez un lien vers Hostelz.com',
    'LinkWithAnImage' => 'Ou si vous voulez un lien avec une image, vous pouvez utilisez ceci à la place:',
    'LooksLikeThis' => 'Cela ressemble à ça...',
];
