<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'actions' => [
        'backlink' => 'Lien retour',
        'ratings' => 'Notes & Avis',
        'video' => 'Vidéo',
    ],
];
