<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'forms' => [
        'fieldLabel' => [
            'address' => 'Adresse',
            'city' => 'Ville',
            'country' => 'Pays',
            'fax' => 'Numéro  de Fax',
            'mailingAddress' => 'Adresse de courrier',
            'name' => 'Nom de l\'hôtel/auberge',
            'ownerName' => 'Nom du Propriétaire',
            'propertyType' => 'Type d’établissement',
            'region' => 'Région',
            'tel' => 'Téléphone',
            'web' => 'Site Internet',
            'zipcode' => 'Code Postal',
        ],
    ],
];
