<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'otherMgmtUsers' => 'L\'accès à la mise à jour de cette entrée a également été autorisé à ces autres utilisateurs:',
    'pleaseComplete' => 'Merci de complèter.',
];
