<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'submitRatingText' => "Avez-vous séjourné dans cet hébergement? Aidez votre communauté d'auberge en laissant un avis détaillé",
    'submitRatingTextLoggedUser' => "Hé :name, tu es resté à l'auberge :hostelName? Laissez votre avis ici.",
    'createAccount' => "<a href=':url'>Créez</a> votre compte gratuit pour garder une trace de votre portefeuille d'auberges.",
];
