<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'ArticleBy' => '投稿者名: :name',
    'Articles' => '記事',
    'ArticlesDesc' => 'Hostelz.comのホステル＆旅行関連記事',
    'h1' => '旅行記事-ブログ',
    'LatestPosts' => '最新の投稿',
];
