<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'Africa' => 'アフリカ',
    'AustraliaOceania' => 'オーストラリア＆オセアニア',
    'CentralEastAsia' => '中央アジア＆東アジア',
    'CentralSouthAmerica' => '中央アメリカ＆南アメリカ',
    'EasternEuropeRussia' => '東ヨーロッパ＆ロシア',
    'MexicoCaribbean' => 'メキシコ＆カリブ海',
    'MiddleEast' => '中東',
    'NorthAmerica' => '北アメリカ',
    'SouthSoutheastAsia' => '南アジア＆東南アジア',
    'UKIreland' => 'イギリス＆アイルランド',
    'WesternEurope' => '西ヨーロッパ',
];
