<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'BecomeAMemberAnswer' => 'HIホステルに滞在するには多くの場合、会員である必要があります。会員でない場合、非会員価格で滞在することができるかもしれませんが、出発前に会員になっておくことをお勧めいたします。<p>HI会員証は世界中で利用することが可能ですが、旅行者の母国にて入会が必要です。',
    'BecomeAMemberQuestion' => 'HIホステルに滞在するには会員になる必要がありますか。',
    'DescriptionOfHI' => 'Hostelling International (HI)は世界的な公式ホステル協会です(前International Youth Hostel Federation ー IYHF)。 HIは６０カ国以上で合計４０００以上のホステル機関を誇る非営利団体です。HIは常に一定水準を保っており、一般的に清潔で安全です。世界の多くの場所で、特に小都市では、HIは唯一のホステルです。(Hostelz.comではHIホステルと提携しておりませんので、HI協会以外のホステルや個人ホステルについても掲載しております)',
    'GetACard' => 'Hostelling Internationalの会員証を申請する',
    'OtherResidents' => 'その他の国の居住者',
    'USResidents' => 'アメリカ市民用',
    'WhatIsHI' => 'HIとは？',
];
