<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'EnterAName' => '都市、国、またはホステル名を入力してください。',
    'ListingsIn' => ':cityCount都市にある:hostelCount件のリスティングを掲載',
    'OnlyWebsiteEverNeed' => '必要な情報を全て網羅したホステル情報サイトです',
    'PopularCities' => 'おすすめの都市',
    'WelcomeTo' => '世界最大級のホステルデータベースへようこそ',
];
