<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'HereIsSomeHTML' => 'Hostelz.comへのリンクを貼って頂きありがとうございます!リンクにはこちらのHTMLをお使いください:',
    'LinkToHostelz' => 'Hostelz.comへのリンク',
    'LinkWithAnImage' => '画像付きのリンクをご希望の場合はこちらをお使いください:',
    'LooksLikeThis' => '表示例',
];
