<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'submitRatingText' => 'あなたはこの宿泊施設に宿泊しましたか？ 詳細なレビューを残すことによって、あなたのホステルのコミュニティを助けます。',
    'submitRatingTextLoggedUser' => 'こんにちは:nameってご宿泊いただく:hostelNameのホステル? ここにあなたのレビューを残す。',
    'createAccount' => 'あなたのホステルのポートフォリオを追跡するためにあなたの無料のアカウント<a href=":url">を作成します</a>。',
];
