<?php

/* dumped from the old website.  may be useful for moving to the new site. */
return [
    'PageTitle' => 'Support a Nonprofit Charity by Linking to Hostelz.com',
    'SignUp' => 'Nonprofits Program',
    'PageText' => 'You can now support a charitable organization of your choice simply by linking to Hostelz.com from your blog or website.  (Or if you are a nonprofit, linking to Hostelz.com is a way you can let people support you in a whole new way.)  <p>When a user clicks the link from your website and makes a booking, <b>100%</b> of the profit generated by the booking goes directly to the nonprofit.  <i>We don\'t keep any of the income generated from bookings made through the link, it all goes directly to the charity you choose.</i> <p>You can choose to donate to organizations including the ASPCA, Red Cross, Kiva, the EFF ... any nonprofit you would like.  To qualify, we usually require that the organization be officially recognized as a charitable nonprofit by a regulatory body in the country where it is located, and the organization must be able to accept donations through PayPal (which includes most charities). <p>Online for more than 10 years, Hostelz.com is the largest and most complete h',
    'Already' => 'Your account (":username") is already registered as an affiliate.  If you would like to have the income you earn as an affiliate go to a nonprofit, or to change the nonprofit that your income goes to, please contact nonprofits@hostelz.com.  You can access the affiliate menu by clicking on your email address at the top of the page.',
    'LoggedinUserActivated' => 'Your account has been granted affiliate access.  If you would like to have the income you earn as an affiliate go to a nonprofit, or to change the nonprofit that your income goes to, please contact nonprofits@hostelz.com.  You can also access the affiliate menu by clicking on your email address at the top of the page.',
];
