<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'BottomNav' => [
        'left' => [
            'link' => 'Packliste für Jugendherbergen',
        ],
        'right' => [
            'link' => 'Empfehlungen für Hostel-Besitzer',
        ],
    ],
];
