<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'ArticleBy' => 'von :name',
    'Articles' => 'Reise Artikel',
    'ArticlesDesc' => 'Alle Artikel über Hostels und Reisebeschreibungen von Hostelz.com.',
    'h1' => 'Reise-Artikel - Blog',
    'LatestPosts' => 'Unsere aktuellen Artikel',
    'otherArticles' => 'Weitere Reise-Artikel von Hostelz.com',
    'readMore' => 'Mehr',
    'welcome' => 'Willkommen auf deinem Hostelz-Blog. Hier dreht sich alles um Hostels, Jugendherbergen und Rucksacktouren. Alles von A bis Z. Wir teilen mit dir unser gesamtes Insiderwissen wie du die besten Hostels, sicher reise, welche Reise-Webseiten du kennen solltest, und natürlich unsere Reise-Hacks. Ganz einfach gesagt: Das hier ist dein Schweizer Taschenmesser rund um Hostels und Backpacking!</p>
<p><em>Der Blog ist aktuell nur auf Englischer Sprache verfügbar.</em>',
];
