<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'AllCities' => 'Unsere Städte in :cities',
    'AllCitiesMapText' => '<p>Okay, du bist eher der visuelle Typ? Wir planen selbst ganz gerne unsere Reisen mit Hilfe einer Karte.</p>

<p>Diese Karte zeigt dir alle Städte mit Hostels und günstigen Unterkünften in :cities. Die Karte wird dir helfen, deine Reise zu planen. Zoome einfach in die Karte und klicke auf dein Reiseziel, um weitere Informationen zu erhalten. Nur damit du Bescheid weißt: Wenn wir kein Hostel für eine bestimmte Stadt gelistet haben, dann gibt es dort keine kein Hostel bzw. Jugendherberge. Denn wir listen alle Hostels auf der ganzen Welt.</p>',
    'AllCitiesMapTitle' => 'Alle :cities Hostels auf einer Karte',
    'AllCitiesText' => '<p>Wir listen hier jede einzelne Hostels in :cities auf. Insgesamt haben wir für dich günstige Unterkünfte in :count Städten in :cities.</p><p>Bitte beachte, dass nicht alle Städte tatsächlich ein echtes Hostel oder Jugendherberge anbieten. Für die Städte ohne Hostels listen wir günstige Unterkünfte wie Pensionen und Gasthäuser. Hier kannst du nach Städten filtern, in denen es eine Jugendherberge/ Hostel oder andere günstige Unterkünfte wie Pension und Budget-Hotels gibt. Das hilft dir bei deiner Planung.</p>',
    'AllTypes' => 'Alle Unterkünfte',
    'cityGroups' => 'Destination',
    'Earplugs' => 'Ohrstöpsel',
    'FAQArea1' => 'Hostels und Preise vergleichen',
    'FAQArea1Schema1' => '<p>Es gibt mehrere Hostel-Buchungsseiten, wie <a href="https://hostelz.com/hw" target="_blank" title="Hostel World">Hostelworld.com</a>, Hostelsclub.com und Booking.com. Obwohl jede Plattform ihre Vor- und Nachteile hat, gibt es eine universelle Wahrheit, die du als Backpacker beachten solltest: Keine einzige Buchungsseite kann immer die besten Preise anbieten.</p><p>Genau da kommt Hostelz.com ins Spiel. Mit Hostelz.com kannst du die Preise auf allen Buchungsplattformen mit 1 Klick vergleichen.</p><p>Für dich als Backpacker ist Hostelz.com die absolut beste Webseite um Hostels und Jugendherbergen zu finden.</p>',
    'FAQArea1Schema2' => '<p>Die Preise variieren immer in Abhängigkeit von verschiedenen Faktoren. Das Wochenende ist in der Regel teurer, genau wie Feiertage. Bitte berücksichtige auch lokale Feiertage und besondere Veranstaltungen wie z.B. Festivals, Stadtfest, eine große Messeausstellung und ähnliches.</p>

<p>Hier auf Hostelz.com kannst du nach genauen Hostelpreisen in :cities suchen. Wähle einfach deine Stadt und ein Datum aus. Das System ermittelt dann die Preise, damit bekommst du eine Vorstellung, welche Preise dich für Hostels in :cities erwarten.</p>',
    'FAQArea1Schema3' => '<p>Wenn du in guten und den besten Hostels übernachten möchtest, dann empfehlen wir, dein Hostel etwa 1 Monat vor Reiseantritt zu reservieren. Für die regulären Hostels sollte eine Buchung eine Woche vorher in Ordnung sein. Dies hängt wiederum immer davon ab, ob es z.B Wochenende oder ein bestimmter lokaler Feiertag ist.</p><p>Wir haben einen detaillierten Artikel darüber geschrieben, <a href=":WhenBookLink" title="beste Zeit Hostel reservieren">wann du am besten dein Hostel reservierst</a>.</p>',
    'FAQArea1Text1' => '<p>Es gibt mehrere Hostel-Buchungsseiten, wie <a href="https://hostelz.com/hw" target="_blank" title="Hostel World">Hostelworld.com</a>, Hostelsclub.com und Booking.com. Obwohl jede Plattform ihre Vor- und Nachteile hat, gibt es eine universelle Wahrheit, die du als Backpacker beachten solltest: Keine einzige Buchungsseite kann immer die besten Preise anbieten.</p><p>Genau da kommt Hostelz.com ins Spiel. Mit Hostelz.com kannst du die Preise auf allen Buchungsplattformen mit 1 Klick vergleichen.</p><p>Für dich als Backpacker ist Hostelz.com die absolut beste Webseite um Hostels und Jugendherbergen zu finden.</p>',
    'FAQArea1Text2' => '<p>Die Preise variieren immer in Abhängigkeit von verschiedenen Faktoren. Das Wochenende ist in der Regel teurer, genau wie Feiertage. Bitte berücksichtige auch lokale Feiertage und besondere Veranstaltungen wie z.B. Festivals, Stadtfest, eine große Messeausstellung und ähnliches.</p>

<p>Hier auf Hostelz.com kannst du nach genauen Hostelpreisen in :cities suchen. Wähle einfach deine Stadt und ein Datum aus. Das System ermittelt dann die Preise, damit bekommst du eine Vorstellung, welche Preise dich für Hostels in :cities erwarten.</p>',
    'FAQArea1Text3' => '<p>Wenn du in guten und den besten Hostels übernachten möchtest, dann empfehlen wir, dein Hostel etwa 1 Monat vor Reiseantritt zu reservieren. Für die regulären Hostels sollte eine Buchung eine Woche vorher in Ordnung sein. Dies hängt wiederum immer davon ab, ob es z.B Wochenende oder ein bestimmter lokaler Feiertag ist.</p><p>Wir haben einen detaillierten Artikel darüber geschrieben, <a href=":WhenBookLink" title="beste Zeit Hostel reservieren">wann du am besten dein Hostel reservierst</a>.</p>',
    'FAQArea1Title1' => 'Welche Hostel Buchungsplattformen sind am besten?',
    'FAQArea1Title2' => 'Was kosten Hostels in :cities? Preise',
    'FAQArea1Title3' => 'Was ist die beste Zeit um Hostels zu reservieren?',
    'FAQArea2' => 'Sicherheit und Packliste',
    'FAQArea2Schema1' => '<p>Ganz allgemein gesagt, sind Hostels so sicher wie du sie selber machst. Wir empfehlen immer ein <a href="https://amzn.to/345SqsM" target="_blank">Vorhängeschloss</a> einzupacken, die Schließfächer zu nutzen und auf die eigenen Dinge aufzupassen. Du solltest auch sicherstellen, dass du immer in sicheren Hostel mit Schließfächern und einer sicheren Nachbarschaft schläfst. Bitte lese dir immer genau die Bewertungen der Hostels durch. Die geben meistens einen guten Einblick was dich erwartet und wie sicher es ist.</p>',
    'FAQArea2Schema2' => '<p>Es gibt ein paar Dinge, die du immer einpacken solltest.</p>',
    'FAQArea2Schema3' => '<p>Das sind die 5 Dinge, die du immer brauchen wirst, aber es gibt natürlich noch mehr. Wir haben eine detaillierte <a href=":WhatPackLink" title="Hostel PackListe list">Packliste für Hostels</a> geschrieben.</p>',
    'FAQArea2Text1' => '<p>Ganz allgemein gesagt, sind Hostels so sicher wie du sie selber machst. Wir empfehlen immer ein <a href="https://amzn.to/345SqsM" target="_blank">Vorhängeschloss</a> einzupacken, die Schließfächer zu nutzen und auf die eigenen Dinge aufzupassen. Du solltest auch sicherstellen, dass du immer in sicheren Hostel mit Schließfächern und einer sicheren Nachbarschaft schläfst. Bitte lese dir immer genau die Bewertungen der Hostels durch. Die geben meistens einen guten Einblick was dich erwartet und wie sicher es ist.</p>',
    'FAQArea2Text2' => '<p>Es gibt ein paar Dinge, die du immer einpacken solltest.</p>',
    'FAQArea2Text3' => '<p>Das sind die 5 Dinge, die du immer brauchen wirst, aber es gibt natürlich noch mehr. Wir haben eine detaillierte <a href=":WhatPackLink" title="Hostel PackListe list">Packliste für Hostels</a> geschrieben.</p>',
    'FAQArea2Title1' => 'Sind Hostels in :cities sicher?',
    'FAQArea2Title2' => 'Was solltest du für eine Jugendherberge und Hostel einpacken?',
    'FAQTopText' => 'Es gibt vor deiner Reise noch einiges zu planen. Wir helfen dir dabei. Wir haben hier einige, häufig gestellte Fragen rund um das Thema Jugendherbergen, Hostels und Unterkünfte zusammengestellt.',
    'FAQTopTitle' => 'FAQ über Hostels in :cities',
    'GuideBackpackingTitle' => 'Unser handgeschriebener Reiseführer zu Backpacking :cities',
    'HeadLamp' => 'LED Kopf-Lampe',
    'HostelsOnly' => 'Nur Hostels',
    'IntroText' => '<p>Du bist also der Suche nach Hostels in :cities. Sehr gut, denn du hast gerade die Webseite gefunden, die deine Reise erheblich einfacher und günstiger machten wird.</p><p>Auf dieser Seite listen wir jede einzelne Stadt in :cities mit Hostels, Jugendherbergen und anderen günstigen Unterkünften. Hostelz.com hilft dir dabei, deine Jugendherberge und Hostel in :cities zu finden. Wir vergleichen für dich die Preise auf den wichtigsten Buchungsseiten wie Hostelworld, Hostelsclub und Booking.com. So kannst du mit kleinem Budget schlafen und beim Backpacken in Nordrhein-Westfalen gutes Geld sparen.</p>',
    'LocalExpertTitle' => 'Handgeschrieben von unserem Local Experten für Hostels in :cities',
    'NoCitiesInformation' => 'Naja...das ist jetzt etwas peinlich, aber wir haben momentan noch keine Reisetipps für :cities. Das heißt wohl, dass wir nach :cities reisen müssen. Wir arbeiten dran!!',
    'Padlock' => 'Vorhängeschloss',
    'QuickDryTowel' => 'Quick-Dry Reisehandtuch',
    'SeeTheFullList' => 'Mehr... Finde hier die komplette Liste von :count Städten mit <a>Hostels in :country</a>.',
    'SleepingMask' => 'Schlafmaske',
    'Submenu1' => 'Alle Städte',
    'Submenu2' => 'Karte',
    'Submenu3' => 'Reiseführer',
    'Submenu4' => 'Tipps',
    'Submenu5' => 'Fragen',
];
