<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'Africa' => 'Afrika',
    'AustraliaOceania' => 'Australien und Ozeanien',
    'CentralEastAsia' => 'Zentral- und Ostasien',
    'CentralSouthAmerica' => 'Zentral- und Südamerika',
    'CountMoreCities' => ':count weitere Städte',
    'EasternEuropeRussia' => 'Osteuropa und Russland',
    'HostelsInCountry' => 'Jugendherbergen in :country',
    'IntroText' => '<p>Du suchst also nach Jugendherbergen und Hostels in Westeuropa? Auf dieser Seite findest du jedes Land und jede Region auf dem Kontinent. Wähle ein Land, Region, eine Stadt oder sogar ein Dorf. Wir haben jedes einzelne Hostel in Westeuropa auf dem Schirm. Von den absolut günstigsten Hostels in Westeuropa bis zu den coolsten und unterhaltsamsten, die du nicht verpassen darfst.</p>

<p>Du bist am Drücker: Wähle dein Land und los geht die Reise!</p>',
    'MexicoCaribbean' => 'Mexiko und Karibische Inseln',
    'MiddleEast' => 'Mittlerer Osten',
    'NorthAmerica' => 'Nordamerika',
    'SeeFullList' => 'Alle Städte',
    'SouthSoutheastAsia' => 'Süd- und Südostasien',
    'UKIreland' => 'GB und Irland',
    'WesternEurope' => 'Westeuropa',
];
