<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'forms' => [
        'options' => [
            'regionType' => [
                'Counties' => 'Kreise',
                'Islands' => 'Inseln',
                'IslandsRegions' => 'Inseln/Regionen',
                'Provinces' => 'Provinzen',
                'ProvincesRegions' => 'Provinzen/Regionen',
                'ProvincesTerritories' => 'Provinzen/Gebiete',
                'Regions' => 'Regionen',
                'States' => 'Staaten',
                'StatesTerritories' => 'States/Gebiete',
            ],
        ],
    ],
];
