<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'closing' => 'Beste Grüße,',
    'initialEmail' => 'Hallo.  :hostelname ist bereits auf Hostelz.com aufgeführt. Ergänze jedoch bitte deinen Eintrag:<br><br> :managementLink<br><br>Unsere Eintragungen sind komplett kostenlos. Das heißt, es wird keine Gebühr für einen Eintrag erhoben. Bitte lasse mich wissen, wenn du eine Frage hast. Danke.',
    'listingIncomplete' => 'Hallo. Deine Informationen deines Eintrags auf Hostelz.com ist nicht vollständig (wir haben womöglich einige Datenfelder seit deinem letzten Besuch ergänzt). Bitte vervollständige deine Informationen deines Eintrags auf Hostelz.com:<br><br> :managementLink<br><br>Natürlich sind Einträge auf Hostelz.com immer kostenlos. Es gibt keine versteckten Gebühren. Bei Fragen bitte melden. Danke.',
    'maybeInitialEmail' => 'Hallo. :hostelname ist bereits auf Hostelz.com aufgeführt. Wir brauchen jedoch ein Update von dir, bitte vervollständige deinen Eintrag:<br><br> :managementLink<br><br>Wir haben neue Features hinzugefügt. Bitte prüfe, ob deine Informationen vollständig und aktuell sind.<br><br>Unsere Eintragungen sind komplett kostenlos. Das heißt, es wird keine Gebühr für einen Eintrag erhoben. Bitte lasse mich wissen, wenn du eine Frage hast. Danke.',
    'newFields' => 'Hallo. Hostelz.com hat kürzlich einige neue Datenfelder in unserer Datenbank ergänzt. Wir bitten dich, einige zusätzliche Informationen deinem Eintrag hinzuzufügen. Bitte aktualisiere:<br><br> :managementLink<br><br>Solltest du eine Frage haben, dann melde dich bitte. Danke.',
    'newlySubmittedListing' => 'Hallo. Danke für das Übertragen von :hostelname auf Hostelz.com. Bitte vervollständige dein Listing:<br><br> :managementLink<br><br>Unsere Eintragungen sind komplett kostenlos. Das heißt, es wird keine Gebühr für einen Eintrag erhoben. Bitte lasse mich wissen, wenn du eine Frage hast. Danke.',
    'TextBelow' => '(Deutsche Übersetzung unten)',
];
