<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'delete' => 'Löschen',
    'deleteAreYouSure' => 'Löschen. Bist du sicher?',
    'dragPhotosToChangeOrder' => 'Du kannst Drag-and-drop verwenden um die Reihenfolge der Bilder zu ändern.',
    'dragToChangeOrder' => 'Du kannst Drag-and-drop verwenden um die Reihenfolge zu ändern.',
    'fileListLabels' => [
        'caption' => 'Caption',
        'filename' => 'Dateiname',
        'filesize' => 'Dateigröße',
    ],
    'view' => 'Ansicht',
];
