<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'BecomeAMemberAnswer' => 'Generell musst du HI-Mitglied sein, um in einem HI-Hostel zu übernachten. Wenn du kein Mitglied bist, ist es möglich durch Aufschlag der Übernachtungskosten dort zu bleiben. Es ist jedoch am besten eine Mitgliedschaftskarte vor Reiseantritt zu erwerben. Mit einer HI-Karte bekommt man weltweit Rabatt auf eine Vielzahl von Reise-relevanten Produkten und Serviceangeboten. <p>Deine HI-Mitgliedschaftskarte kann in jedem Hostel weltweit genutzt werden, doch eine Mitgliedschaftskarte muss von einer HI-Organisation des Heimatlandes ausgestellt sein.',
    'BecomeAMemberQuestion' => 'Muss ich Mitglied sein, um in einem HI-Hostel zu übernachten?',
    'DescriptionOfHI' => 'Hostelling International (HI) ist die "offizielle" weltweite Hostel-Organisation (auch bekannt als "International Youth Hostel Federation", oder IYHF). HI ist eine gemeinnützige Organisation, welche Herbergsverbände in über 60 Ländern mit insgesamt über 4000 Hostels vertritt. HI-Hostels garantieren ein bestimmtes Maß an Qualität und sind generell sauber und sicher. Und in vielen Teilen der Welt, insbesondere in kleineren Städten, sind HI-Hostels möglicherweise die einzigen Hostels der Stadt. (Übrigens, Hostelz.com ist nicht mit HI oder irgend einer anderen Vereinigung verbunden. Wir listen sowohl HI-Hostels, Hostels die zu anderen Herbergsverbänden gehören als auch unabhängige Hostels.)',
    'GetACard' => 'Erwerbe eine Hostelling International Mitgliedschaftskarte...',
    'OtherResidents' => 'Für Staatsbürger anderer Länder',
    'USResidents' => 'Für US-Staatsbürger',
    'WhatIsHI' => 'Was bedeutet HI?',
];
