<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'translated' => [
        'de' => 'Deutsch',
        'en' => 'Englisch',
        'es' => 'Spanisch',
        'fr' => 'Französisch',
        'it' => 'Italienisch',
        'ja' => 'Japanisch',
        'pt-br' => 'Portugiesisch',
    ],
];
