<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'HereIsSomeHTML' => 'Danke, dass du auf deiner Webseite zu Hostelz.com linkst. Hier ist ein Beispiel in HTML Format, das du kopieren kannst, um auf unsere Seite zu linken.',
    'LinkToCity' => 'Linke zu einer speziellen Stadt',
    'LinkToCityChangeText' => 'Bitte denke daran, den Namen der Stadt im Link zu ersetzen. Du findest den korrekt Link, indem du nach der Stadt auf Hostelz.com suchst.',
    'LinkToHostelz' => 'Verlinke auf Hostelz.com',
    'LinkToHostelzText' => 'Wir sind in erster Linie eine Informations-Webseite und Datenbank für Hostels und Jugendherbergen weltweit. Wir sind auf Word of Mouth, Reiseblogs und die Online Community angewiesen. Wenn du eine Webseite, eine Nachrichten Seite, Magazin oder Reise Blog besitzt, dann kannst du uns ganz einfach unterstützen. </p><p>Bitte verlinke unsere Seite von deinem Medium wie Blog, Webseite oder Social Media. Jeder Link hilft und wir sind für jede Hilfe dankbar.',
    'LinkToHTMLTitle' => 'HTML Code für Copy-und-Paste',
    'LinkToStartPage' => 'Linke zu unserer Start Seite',
    'LinkWithAnImage' => 'Wenn du einen Link mit Bild setzen willst, kannst du folgenden Code kopieren.',
    'LinkWithAnImageTitle' => 'Logo einbetten',
    'LinkWithBlogText' => 'Wir haben außerdem detaillierte Reiseführer zu zahlreichen Hostel Themen geschrieben. Wir schreiben über Sicherheits Tipps für Hostels, wie du die besten Hostels auswählst und mehr.',
    'LinkWithBlogTextRead' => 'Lese den Hostel Blog hier',
    'LinkWithJournalistContact' => 'Kontakt',
    'LinkWithJournalistText' => 'Bist du auf der Suche nach mehr Informationen und Daten zu Jugendherbergen und Hostels weltweit? Wir sind offen für Interviews und Medienanfragen über Hostels und Backpacking. Bitte kontaktiere uns.',
    'LinkWithJournalistTitle' => 'Bist du ein Journalist oder Blogger?',
    'LooksLikeThis' => 'So sieht es aus ...',
    'Partner' => 'Partner',
];
