<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'comment' => 'Andere Korrekturen',
    'ListingCorrection' => 'Aktualisierung des Eintrags & Korrekturen',
    'ListingCorrectionReturnText' => 'Deine Vorschläge werden nach Prüfung unserer Mitarbeiter veröffentlicht.',
    'ListingCorrectionReturnTitle' => 'Aktualisierung übermittelt. Vielen Dank.',
    'NoChangesMade' => 'Keine Veränderungen durchgeführt. Die Aktualisierung des Eintrages wird abgebrochen.',
    'OwnerContactUs' => 'Bist du der Besitzer dieser Unterkunft? <a href=":contactlink" title="contact Hostelz">Kontaktiere uns</a> um Informationen wie du dein Listing auf Hostelz.com bearbeiten und aktualisieren kannst.',
    'Return' => 'Zurück zum Hostel Profil',
    'ThisFormIs' => 'DIESES FORMULAR DIENT ALS KORREKTURMÖGLICHKEIT DER GELISTETEN INFORMATIONEN EINES BESTIMMTEN HOSTELS.</b> Hostelz.com kann keine Fragen zu diesem Hostel beantworten. Wenn du versuchst, ein bestimmtes Hostel oder ein Hotel direkt zu erreichen, gehe zurück und suche nach Kontaktinformationen oben auf der Webseite des Hosteleintrags. Jegliche Kontaktinformation die wir haben (wie bspw. Webseite oder Telefonnummer) wird dort aufgeführt. Wenn du Hostelz.com kontaktieren möchtest, nutze unser Kontaktformular auf der Website unter "Kontakt".',
];
