<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'AnyQuestions' => 'Wenn du irgendwelche Fragen zu dem Eintrag deiner Unterkunft hast, bitte kontaktiere uns.',
    'featuredListing' => 'Featured Listing',
    'Information' => 'Information',
    'otherMgmtUsers' => 'Hinweis: Diese anderen Nutzer haben auch Zugang zu diesem Listing:',
    'pleaseComplete' => 'Fülle bitte aus.',
    'preview' => 'Vorschau',
    'Status' => 'Status',
    'SuggestionsForHostelOwners' => 'Empfehlungen für Hostel Besitzer',
    'view' => 'Listing anschauen',
];
