<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'Cookies' => [
        'title' => 'Cookies',
    ],
    'PageTitle' => 'Datenschutzrichtlinie',
    'ProtectInfo' => [
        'title' => 'Wie wir deine Daten schützen',
    ],
    'Registration' => [
        'title' => 'Registrierung',
    ],
    'SharingInfo' => [
        'title' => 'Teilen von Informationen',
    ],
];
