<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'citiesMatches' => 'Übereinstimmungen Stadt',
    'cityGroupsMatches' => 'Übereinstimmungen zur Region',
    'continentsMatches' => 'Übereinstimmungen Kontinent',
    'countriesMatches' => 'Übereinstimmungen Land',
    'listingsMatches' => 'Übereinstimmungen Unterkunft',
    'NoMatchesFor' => 'Es tut uns leid, doch es wurden keine Übereinstimmungen für ":search" gefunden.',
    'regionsMatches' => 'Übereinstimmungen Region',
    'SearchResults' => '":searchText" Suchergebnisse',
];
