<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'BestHostelsMetaText' => 'Liste von 13 BESTEN Hostels in :city in :year (Preise ab $:lowestDormPrice)',
    'BestHostelsMetaTitle' => '13 BESTEN Hostels in :city in :year (ab $:lowestDormPrice)',
    'BlogMetaDescription' => 'Beste Hostel Reise Blog der Welt. Lerne alles über Jugendherbergen, Hostels, Solo-Reisen und Backpacken.',
    'BlogMetaTitle' => 'Hostelz Blog :year - der beste Hostel Blog zum Backpacken, Hostels und um Alleine zu Reisen',
    'CitiesMetaDescription' => 'Komplete Liste aller Hostels in :area in :year - mit allen Städten. Backpacker Hostels, Jugendherbergen, Youth Hostels, Familien Hostels. Preisvergleich auf Hostelworld und Booking.com (spare bis zu 13%)',
    'CitiesMetaTitle' => 'Alle Hostels in :area :year (Preisvergleich auf Hostelworld und Booking.com)',
    'CityMetaDescription' => 'Die BESTEN Hostels in :city in :year. Vergleiche :count Hostels und Jugendherbergen in :city. Preisvergleich mit Hostelworld und Booking.com (spare bis zu 13%)',
    'CityMetaTitle' => 'BESTEN Hostels in :city :year (ab $:lowestDormPrice) - Preisvergleich',
    'CityMetaTitle1Hostel' => '1 Hostel in :city, :area :year (Preisvergleich Hostelworld und Booking.com)',
    'CityMetaTitleBackpackers' => ':count Hostels in :city :year (Preisvergleich mit Hostelworld und Booking.com)',
    'ContinentsMetaDescription' => 'Finde alle Hostels in :area in :year - mit allen Ländern. Backpacker Hostels, Jugendherbergen, Youth Hostels, Familien Hostels. Preisvergleich mit Hostelworld und Booking.com (spare bis zu 13%)',
    'ContinentsMetaTitle' => 'Alle Hostels in :area :year (Preisvergleich mit Hostelworld und Booking.com)',
    'IndexMetaDescription' => 'Die Beste Hostel Buchungsplattform weltweit :year.  - :TotalHostelCountHostels und Jugendherbergen weltweit. Vergleiche Preise auf Hostelworld und Booking.com mit 1 Klick.',
    'IndexMetaTitle' => 'Hostel Preisvergleich :year - Hostelz.com - die Besten Hostels Weltweit',
    'ListingMetaDescription' => 'Ist :hostelName das beste Hostel in :city? Echte Bewertungen von :hostelName in :year mit Video, Fotos und Preisen (Spare bis zu 17%)',
    'ListingMetaTitle' => ':hostelName in :city - Preisvergleich :year auf Hostelworld und Booking.com (17% billiger)',
];
