<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'SubmitListing' => 'Hostel hinzufügen',
    'SubmitListingInfo' => 'Bevor du ein neues Hostel hinzufügst, suche es bitte über die Suchmaske oben, um sicherzustellen, dass das Hostel nicht bereits auf unserer Website gelistet ist. Alle Hostel-Angebote auf unserer Website sind komplett kostenlos. Neue Hostels müssen eine eigene Website besitzen (eine Facebook-Seite ist ausreichend, eine Buchungswebsite eines Drittanbieters jedoch nicht). Hostels ohne Webseite können derzeit nicht hinzugefügt werden.',
    'SubmitListingReturnText' => 'Der neue Eintrag wird der Webseite hinzugefügt, nachdem es genehmigt wurde. <br> <br> Alle Einträge auf unserer Website sind kostenlos. Das einzige, was wir im Gegenzug verlangen, ist, dass du auf deiner Webseite einen Link zu Hostelz.com hinzufügst (http://www.hostelz.com). Es gibt HTML und ein Bild, die du mit Hilfe <a href="[linkToUsURL‹"> <b> hier </ b> </a> verwenden kannst.',
    'SubmitListingReturnTitle' => 'Neues Listing wurde gesendet.',
];
