<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'createList' => 'Erstelle eine Liste',
    'createNewList' => 'Erstelle eine neue Liste',
    'deleteList' => 'Liste löschen',
    'Listing' => 'Auflistung',
    'listName' => 'Hostel/Hotel Name',
    'modalDeleteBodyText' => 'Bist du sicher, dass du löschen möchtest?',
    'modalDeleteBtnYes' => 'Ja, löschen',
    'noListings' => 'Keine Auflistungen',
    'nothingSaved' => 'Noch nichts gespeichert',
    'removedFrom' => 'Entfernt von',
    'savedList' => 'Gespeicherte Liste',
    'savedLists' => 'Gespeicherte Listen',
    'savedTo' => 'Gespeichert',
    'saveToList' => 'In einer Liste speichern',
    'stays' => 'Übernachtungen',
    'Wishlists' => 'Wunschliste',
];
