<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'ArticleBy' => 'Escrito por :name',
    'Articles' => 'Artículos de viaje',
    'ArticlesDesc' => 'Artículos sobre albergues, hostales y viajes en Hostelz.com.',
    'h1' => 'Artículo de viaje - Blog',
    'LatestPosts' => 'Últimos artículos',
    'otherArticles' => 'Más artículos sobre hostales',
    'readMore' => 'Dame más (info)',
    'welcome' => '¡Hola mochilero! Bienvenido al blog de Hostelz, donde hablamos sobre hostales, backpacking, y viajar barato. 
Aquí compartimos todo lo que sabemos sobre hostales (¡que no es poco!), páginas web que nos gustan y utilizamos para explorar el mundo, y por supuesto, también añadimos nuestros mejores trucos para poder viajar más tiempo y de forma más económica. 
Nuestro objetivo es que éste sea un lugar donde encuentres toda la información que necesitas para viajar barato.',
];
