<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'Africa' => 'África',
    'AustraliaOceania' => 'Australia y Oceanía',
    'CentralEastAsia' => 'Asia Central y del Este',
    'CentralSouthAmerica' => 'América Central y Sudamérica',
    'CountMoreCities' => ':count lugares más',
    'EasternEuropeRussia' => 'Europa del Este y Rusia',
    'HostelsInCountry' => 'Hostales en :country',
    'IntroText' => 'Estás buscando hostales en :continent? En esta página encontrarás todas los países y regiones de la zona. Elige un país, región, ciudad o pueblo. Mencionamos todos los hostales en :continent. Desde el hostal más barato en :continent hasta el más guay, y por supuesto, todos aquellos que no deberías perderte.  </p><p>Elige un país y...  explora!</p>',
    'MexicoCaribbean' => 'México y el Caribe',
    'MiddleEast' => 'Oriente Medio',
    'NorthAmerica' => 'América del Norte',
    'SeeFullList' => 'Todos los lugares',
    'SouthSoutheastAsia' => 'Asia del Sur y Sudeste',
    'UKIreland' => 'Reino Unido e Irlanda',
    'WesternEurope' => 'Europa del Oeste',
];
