<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'forms' => [
        'options' => [
            'regionType' => [
                'Counties' => 'Condados',
                'Islands' => 'Islas',
                'IslandsRegions' => 'Islas/ Regiones',
                'Provinces' => 'Provincias',
                'ProvincesRegions' => 'Provincias/ Regiones',
                'ProvincesTerritories' => 'Provincias/ Territorios',
                'Regions' => 'Regiones',
                'States' => 'Estados',
                'StatesTerritories' => 'Estados/ Territorios',
            ],
        ],
    ],
];
