<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'closing' => 'Atentamente.',
    'initialEmail' => 'Hola. :hostelname ya está listado en Hostelz.com, pero necesitamos que complete la información de su anuncio:<br><br> :managementLink<br><br>Nuestros anuncios son totalmente gratuitos, por lo tanto no hay ningún cargo por estar publicado en nuestro sitio. No dude en contactarse conmigo si tiene alguna pregunta. Gracias.',
    'listingIncomplete' => 'Hola. Su información en el anuncio en Hostelz.com está incompleta (hemos agregado algunos nuevos campos desde la última vez que ingresó su información). Por favor, completa la información en su anuncio en Hostelz.com:<br><br> :managementLink<br><br>Obviamente, los anuncios en Hostelz.com son siempre gratuitos, no hay ningún cargo por estar publicado en nuestro sitio. Si tiene alguna pregunta, póngase en contacto conmigo.',
    'maybeInitialEmail' => 'Hola.  :hostelname ya está listado en Hostelz.com. Aquí hay un formulario en línea para completar o editar la información de su publicidad:<br><br>  :managementLink<br><br>Recientemente hemos agregado nuevas funciones, incluyendo la posibilidad de ingresar descripciones de su publicación en diferentes idiomas. Por favor verifique que toda su información esté completa y actualizada.<br><br>Como siempre, nuestros listados son totalmente gratuitos, por lo tanto no hay ningún cargo por estar publicado en el sitio. No dude en contactarse conmigo si tiene alguna pregunta. Gracias.',
    'newFields' => 'Hola. Hostelz.com ha agregado recientemente algunos nuevos campos a nuestra base de datos y es necesario que nos complete alguna información adicional para incluirla en su publicidad. Por favor actualice su publicidad:<br><br> :managementLink<br><br> En caso de tener alguna pregunta, póngase en contacto conmigo.',
    'newlySubmittedListing' => 'Hola.  Gracias por enviar :hostelname a Hostelz.com.  Por favor complete la información de su anuncio:<br><br> :managementLink<br><br>Nuestros anuncios son totalmente gratuitos, por lo cual no existe ningún cargo por estar publicado en el sitio. No dude en contactarse conmigo si tiene alguna pregunta. Gracias.',
    'TextBelow' => '(Traducción al español a continuación)',
];
