<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'delete' => 'Borrar',
    'deleteAreYouSure' => 'Borrar. ¿Estás seguro?',
    'dragPhotosToChangeOrder' => 'Puedes cambiar el orden de las fotos arrastrándolas',
    'dragToChangeOrder' => '(Puedes arrastrar las fotos para cambiar el orden)',
    'fileListLabels' => [
        'caption' => 'Descripción',
        'filename' => 'Nombre',
        'filesize' => 'Tamaño',
    ],
    'view' => 'Ver',
];
