<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'BecomeAMemberAnswer' => 'Generalmente es necesario ser miembro para hospedarse en un albergue HI. En caso de no ser miembro, se podrá hospedar pagando un cargo extra por noche, pero es preferible comprar una membresía antes comenzar su viaje. Con una tarjeta HI también obtendrá descuentos en miles de artículos y servicios de viaje en todo el mundo. <p>Su tarjeta de membresía HI puede utilizarse en albergues de cualquier parte del mundo, pero la tarjeta de membresía deberá ser adquirida en la asociación HI de su país de residencia.',
    'BecomeAMemberQuestion' => '¿Necesito ser miembro para hospedarme en un albergue HI?',
    'DescriptionOfHI' => 'Hostelling International (HI) es la organización "oficial" de albergues juveniles a nivel mundial (solía llamarse International Youth Hostel Federation, o IYHF). HI es una organización sin fines de lucro que representa asociaciones de albergues juveniles en más de 60 países, con un total que supera los 4000 albergues. Los albergues HI mantienen determinado nivel de calidad y por lo general son limpios y seguros. Además, en muchos lugares del mundo, especialmente en ciudades pequeñas, el albergue HI probablemente sea el único albergue de la ciudad. (Por cierto, Hostelz.com no está afiliado con HI ni con ningún otro grupo. Nosotros publicamos albergues HI , albergues pertenecientes a otros grupos de albergues y también listamos albergues independientes.)',
    'GetACard' => 'Obtener una tarjeta de membresía Hostelling International...',
    'OtherResidents' => 'Para residentes de otros países',
    'USResidents' => 'Para residentes de los EEUU',
    'WhatIsHI' => '¿Qué es HI?',
];
