<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'translated' => [
        'de' => 'Alemán',
        'en' => 'Inglés',
        'es' => 'Español',
        'fr' => 'Francés',
        'it' => 'Italiano',
        'ja' => 'Japonés',
        'pt-br' => 'Portugués (Brasileño)',
    ],
];
