<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'HereIsSomeHTML' => '¡Gracias por agregar un enlace con Hostelz.com en su sitio web! Aquí hay una muestra HTML que puede usarse como enlace a nuestro sitio:',
    'LinkToHostelz' => 'Enlazar a Hostelz.com',
    'LinkWithAnImage' => 'O si desea una imagen como enlace, puede utilizar ésta:',
    'LooksLikeThis' => 'Se ve así...',
];
