<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'comment' => 'Otras correcciones',
    'ListingCorrection' => 'Correcciones y actualización del listado',
    'ListingCorrectionReturnText' => 'Sus sugerencias aparecerán en el listado después que hayan sido aprobadas por nuestro personal.',
    'ListingCorrectionReturnTitle' => 'Actualización enviada. Muchas gracias.',
    'NoChangesMade' => 'No se han realizado cambios. Actualización de listado cancelada.',
    'OwnerContactUs' => '¿Es usted el propietario de este hostal? <a href=":contactlink" title="contact Hostelz">Contactenos aquí</a> para informarse cómo puede modificar su listing.',
    'Return' => 'Vuelva al listing',
    'ThisFormIs' => 'ESTE FORMULARIO ES PARA HACER CORRECCIONES EN LA INFORMACIÓN DE ESTA LISTA DE ALBERGUES.</b> Hostelz.com no puede contestar preguntas sobre este albergue. Si está intentando ponerse en contacto con un albergue u hotel en particular, regrese al anuncio del albergue y busque la información de contacto donde dice Localización/Contacto.  Cualquier información de contacto que tengamos (tales como un sitio web o número de teléfono) estará incluida en el listado. Si desea ponerse en contacto con Hostelz.com, utilice el enlace "Contactarse con Hostelz.com" que se encuentra más abajo.',
];
