<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'Cookies' => [
        'title' => 'Cookies',
    ],
    'PageTitle' => 'Política de privacidad',
    'Registration' => [
        'p1' => 'No es necesario registrate para utilizar esta web. Para algunos servicios especiales, como publicar comentarios o reviews, se requerirá un e-mail válido. Simplemente te enviaremos un email de confirmación de dirección. No te añadiremos a ninguna lista de correos y no enviaremos ningún otro email a la dirección proporcionada.',
        'title' => 'Registro',
    ],
];
