<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'citiesMatches' => 'Coincidencias con la Ciudad',
    'cityGroupsMatches' => 'Coincidencias con la Zona',
    'continentsMatches' => 'Coincidencias con el Continente',
    'countriesMatches' => 'Coincidencias con el País',
    'listingsMatches' => 'Coincidencias con el Alojamiento',
    'NoMatchesFor' => 'Lo sentimos, no se encontró información sobre ":search".',
    'regionsMatches' => 'Coincidencias con la Región',
    'SearchResults' => '":searchText" Resultados de la Búsqueda',
];
