<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'BestHostelsMetaText' => 'Lista de los 13 mejores hostales en :city :year. Precios desde $:lowestDormPrice',
    'BestHostelsMetaTitle' => '13 Mejores hostales en :city :year (desde $:lowestDormPrice)',
    'BlogMetaDescription' => 'El mejor blog de viajes sobre hostales en el mundo. Todo lo que necesitas saber sobre hostales, viajar solo y viajar barato.',
    'BlogMetaTitle' => 'Blog Hostelz :year- Todo sobre hostales, viajar barato y viajar solo',
    'CitiesMetaDescription' => 'Encuentra todos los albergues y hostales en :area en :year -  Compara precios (y ahorra hasta el 13%) en 1 solo clic',
    'CitiesMetaTitle' => 'Todos los hostales en :area :year - Comparador de precios',
    'CityMetaDescription' => 'Compara :count hostales baratos en :city en :year. Comparación rápida (en un clic). Ahorra hasta 13%!',
    'CityMetaTitle' => 'Todos los hostales en :city :year (desde $:lowestDormPrice)',
    'CityMetaTitle1Hostel' => 'Mejor hostal en :city :year - Comparador de precios instantáneo',
    'CityMetaTitleBackpackers' => ':count Albergues y hostales en :city :year (Reserva la mejor oferta)',
    'ContinentsMetaDescription' => 'Encuentra todos los alberges y hostales en :area en :year -  Compara precios (y ahorra hasta el 13%) en 1 solo clic',
    'ContinentsMetaTitle' => 'Todos los hostales en :area :year (Ahorra dinero en un solo clic)',
    'IndexMetaDescription' => 'La mejor plataforma de reservas de hostales del mundo :year.  :TotalHostelCount hostales en todo el mundo. Compara precios en 1 solo clic en Booking.com y Hostelworld.',
    'IndexMetaTitle' => 'Comparación de precios rápida e inteligente :year - :TotalHostelCount hostales en todo el mundo',
    'ListingMetaDescription' => 'Es :hostelName el mejor hostal en :city? Opinión honesta de :hostelName :year con video, fotos y precios (ahorra hasta el 17%)',
    'ListingMetaTitle' => ':hostelName en :city - Vale la pena? (Precios comparados en todas las plataformas)',
];
