<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'SubmitListing' => 'Agregar un nuevo hostal',
    'SubmitListingInfo' => 'Antes de añadir un nuevo hostal, por favor utiliza la herramienta de "buscar" para asegurarte que el hostal no está en nuestra base de datos. Todos los hostales en nuestra web son alistados de forma gratuita. Los nuevos hostales añadidos en esta web deben tener su propia página web (una fanpage de Facebook es aceptable solamente si es todo lo que tienen, pero no otras se aceptarán enlaces a otras plataformas de reserva). Los hostales sin página web no pueden ser añadidos en estos momentos.',
    'SubmitListingReturnText' => 'Este nuevo listing será añadido en la web una vez haya sido aprobado.  <br><br>Todos los listings en nuetra web son gratuitos. Lo único que pedimos a cambio es que añadas un link a Hostelz.com (www.hostelz.com) en tu website. <a href=":linkToUsURL"><b>Aquí</b></a> tienes las instrucciónes y un HTML e imagines que puedes utilizar.',
    'SubmitListingReturnTitle' => 'Nueva publicación enviada.',
];
