<?php

/* GENERATED BY LanguageString::updateLangFiles() */
return [
    'createList' => 'Crear una lista',
    'createNewList' => 'Crea una nueva lista',
    'deleteList' => 'Eliminar esta lista',
    'Listing' => 'Listado',
    'listName' => 'Nombre',
    'modalDeleteBodyText' => '¿Estás seguro que quieres borrarla?',
    'modalDeleteBtnYes' => 'Si, borrar',
    'noListings' => 'Sin listados',
    'nothingSaved' => 'Nada guardado todavía',
    'removedFrom' => 'Eliminado de',
    'savedList' => 'Lista guardada',
    'savedLists' => 'Listas guardadas',
    'savedTo' => 'Guardado en',
    'saveToList' => 'Guardar en una lista',
    'stays' => 'Hospedaje| Estancias',
    'Wishlists' => 'Listas de deseos',
];
